dist: bionic

language: node_js

node_js:
  - 13.14.0

script:
  - yarn eslint
  - yarn coverage

travis encrypt "$LANGUAGE_POWER:$SLACK_TOKEN" --add notifications.slack

notifications:
slack: $LANGUAGE_POWER:$SLACK_TOKEN

# notifications:
#   slack:
#     rooms:
#   - $LANGUAGE_POWER: $SLACK_TOKEN
