dist: bionic

language: node_js

node_js:
  - 13.14.0

script:
  - yarn eslint
  - yarn coverage

notifications:
slack:
  secure: 'h+nc7hOxjlQfrurmn+0Q71Tut+bzKz33JR3xS3cvYX0u8IbG42PEPm3H8I9P7W0XLHjNyLpNwOtTMvjj2zft8x1E3IPKtxuv0tcRkKoDKrG3/bdp29ZpDr1GqK0WQ7VibSAUxXGu1k8PvmeuKUoITlHUREljOgBggcaKzGae2Mimzi2IVwjRdbGL/dVNR71cDUIBoWz8AKCG79bR4N8Y/aa7yIeiKKcc+gRVnn/eApFCVDNyVwfXWcSVhqMf3ROlsi7A2C2cRzMVvlYbDSUp5z8TLxycg6AG2eIyILL+kamey/KRDX/7swC9M0sx9nlHTacJzt4I3cYjuNsf8q86UyHALi2r+m0t11YnTrCK/aOAheb3i4TL1PJY7AENo9/Ss39OQZ4XL+YFdf6axcd1ARLTxHB2sFZdMiMwkd25T19N/3qO+1VdQ+w60W3egxktVccVvPK/NRDUAF4V8XL0jVam6NfbK7mmbRnbl/euATJWgetukS1eSPBF5SZDr0aKe36iAx7gqHlrxt1qYg+qEdKMJCRthAkn7IFRkk4TotunD29IpOnBy1NWWwdbguiN3G1TBq5HMLtlWFWbXPrC9ZtAf8hMEYOMQl7al+4kdfVaWzKKe2hF6yZlVVL4XUMoIlFhG1rW1IEGIh2rJ+memTtwrHSdPhWCBznLIrB4ZRs='
